/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ncfqgihxindeteslboou"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZnFnaWh4aW5kZXRlc2xib291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwODk1NjcsImV4cCI6MjA4ODY2NTU2N30.LP-hebYgqje-obnw1HxmArZ9P6YGHdnWYEgMJwkwgG0"